pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/AlapatiChandrasekhar/PES2UG22CS052_Jenkins.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                sh 'g++ CC_TA-main/CC_TA-main/main/new_hello.cpp -o CC_TA-main/CC_TA-main/main/hello_exec'
            }
        }

        stage('Test') {
            steps {
                sh './CC_TA-main/CC_TA-main/main/hello_exec'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Application'
            }
        }
    }

    post {
        failure {
            error 'Pipeline failed'
        }
    }
}
