pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/AlapatiChandrasekhar/PES2UG22CS052_Jenkins.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                dir('CC_TA-main/CC_TA-main/main') { // Navigate to the correct folder
                    sh 'g++ new_hello.cpp -o hello_exec'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CC_TA-main/CC_TA-main/main') { // Run from correct directory
                    sh './hello_exec'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Application'
            }
        }
    }

    post {
        failure {
            error 'Pipeline failed'
        }
    }
}
